service: pact

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB: ${self:custom.secrets.DB}
    NEO4J_HOST: ${self:custom.secrets.NEO4J_HOST}
    NEO4J_USER: ${self:custom.secrets.NEO4J_USER}
    NEO4J_PASSWORD: ${self:custom.secrets.NEO4J_PASSWORD}

functions:
  verify-token:
    handler: auth/VerifyToken.auth

  login:
    handler: auth/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: auth/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  # pacts
  getUserPacts:
    handler: pact/PactHandler.getUserPacts
    events:
      - http:
          path: getUserPacts
          method: get
          cors: true

  getPactInfo:
    handler: pact/PactHandler.getPactInfo
    events:
      - http:
          path: getPactInfo
          method: get
          cors: true

  createPact:
    handler: pact/PactHandler.createPact
    events:
      - http:
          path: createPact
          method: post
          cors: true

  deletePact:
    handler: pact/PactHandler.deletePact
    events:
      - http:
          path: deletePact
          method: delete
          cors: true

  updatePact:
    handler: pact/PactHandler.updatePact
    events:
      - http:
          path: updatePact
          method: put
          cors: true

  # friends
  get-friends:
    handler: friends/FriendsHandler.getFriends
    events:
      - http:
          path: friends
          method: get
          cors: true

  get-requests:
    handler: friends/FriendsHandler.getRequests
    events:
      - http:
          path: friends/request
          method: get
          cors: true

  send-request:
    handler: friends/FriendsHandler.sendRequest
    events:
      - http:
          path: friends/request/send
          method: post
          cors: true

  accept-request:
    handler: friends/FriendsHandler.acceptRequest
    events:
      - http:
          path: friends/request/accept
          method: post
          cors: true

  decline-request:
    handler: friends/FriendsHandler.declineRequest
    events:
      - http:
          path: friends/request/decline
          method: post
          cors: true

plugins:
  - serverless-offline
